

# This file was *autogenerated* from the file attack.sage
from sage.all_cmdline import *   # import sage library

_sage_const_300 = Integer(300); _sage_const_0 = Integer(0); _sage_const_20 = Integer(20); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_10 = Integer(10); _sage_const_9 = Integer(9); _sage_const_1000 = Integer(1000); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_10000 = Integer(10000); _sage_const_101 = Integer(101); _sage_const_50 = Integer(50); _sage_const_5 = Integer(5)##################################################
# RING-LWE ATTACK #
##################################################

# General preparation of Sage: Create a polynomial ring and import GaussianSampler, Timer
P = PolynomialRing(RationalField(), 'y', names=('y',)); (y,) = P._first_ngens(1)
from sage.stats.distributions.discrete_gaussian_lattice import DiscreteGaussianDistributionLatticeSampler
RP = RealField(_sage_const_300 ) # sets the precision
from sage.doctest.util import Timer

# Give the Minkowski lattice for a given ring determined by a polynomial.
def cmatrix(): 
    global N, a
    N = NumberField(f, names=('a',)); (a,) = N._first_ngens(1)
    fdeg = f.degree()
    key = [_sage_const_0  for i in range(fdeg)] # 0 = real, 1 = real part, 2 = imaginary part
    embs = N.embeddings(CC)
    M = matrix(RP, fdeg, fdeg)
    
    print("Preparing an embedding matrix: computing powers of the root.")
    apows = [a**j for j in range(n)]
    print("Finished computing the powers of the root.")
    
    i = _sage_const_0 
    while i < n:
        em = embs[i]
        if Mod(i, _sage_const_20 ) == _sage_const_0 :
            print(f"Embedding matrix: {i} rows out of {n} complete.")
        
        if em(a).imag() == _sage_const_0 :
            key[i] = _sage_const_0 
            for j in range(n):
                M[i, j] = em(apows[j]).real()
            i = i + _sage_const_1 
        else:
            key[i] = _sage_const_1 
            key[i+_sage_const_1 ] = _sage_const_2 
            for j in range(n):
                M[i, j] = em(apows[j]).real()
                M[i+_sage_const_1 , j] = (em(apows[j]) * I).real()
            i = i + _sage_const_2 
    return M, key

# Produce a random vector from (Z/qZ)^n
def random_vec(q, dim):
    return vector([ZZ.random_element(_sage_const_0 , q) for i in range(dim)])

# Useful function for real numbers modulo q
def modq(r, q):
    t = r/q - floor(r/q)
    return t*q

# Call sampler
def call_sampler():
    e = sampler().change_ring(RP)
    return e

# Create samples using a lattice
def get_sample(latmat, latmatinv, sec, qval, keyval):
    e = call_sampler() 
    dim = latmat.dimensions()[_sage_const_0 ]
    pre_a = random_vec(qval, dim)
    a_vec = latmat * pre_a 
    b_vec = vecmul_poly(a_vec, sec, latmat, latmatinv) + e
    pre_b = latmatinv * b_vec
    pre_b_red = vector([modq(c, qval) for c in pre_b])
    b_vec = latmat * pre_b_red
    return [a_vec, b_vec]

# Global choices: setup dummy values
q = _sage_const_1 
n = _sage_const_1 
sig = _sage_const_1 /sqrt(_sage_const_2 *pi)
Zq = IntegerModRing(q)
R = PolynomialRing(Zq, names=('x',)); (x,) = R._first_ngens(1)
f = y + _sage_const_1 
N = NumberField(f, names=('a',)); (a,) = N._first_ngens(1)
S = R.quotient(f, names=('z',)); (z,) = S._first_ngens(1)
cm, key = matrix(RP, _sage_const_1 , _sage_const_1 , [_sage_const_0 ]), []
cmi = cm

# Set the parameters for the attack
def setup_params(fval, qval, sval):
    global q, n, sig, f, S, x, z, Zq
    f = fval
    n = f.degree()
    q = qval
    Zq = IntegerModRing(q)
    R = PolynomialRing(Zq, names=('x',)); (x,) = R._first_ngens(1)
    sig = sval/sqrt(_sage_const_2 *pi)
    S = R.quotient(f, names=('z',)); (z,) = S._first_ngens(1)
    print(f"Setting up parameters, poly = {f}, prime = {q}, sigma = {sig}")
    print("Verifying properties: ")
    print("Prime?", q.is_prime())
    print("Irreducible? ", f.is_irreducible())
    print("Value at 1 modulo q?", Mod(f.subs(y=_sage_const_1 ), q))
    return True

# Compute the lattices in Minkowski space
def prepare_matrices():
    global cm, key, cmi, cmqq
    print("Preparing matrices.")
    cm, key = cmatrix()
    cmi = cm.inverse()
    cm53 = cm.change_ring(RealField(_sage_const_10 ))
    cmqq = cm53.change_ring(QQ)
    print("All matrices prepared.")
    return True

# Make a vector in R^n into a polynomial
def make_poly(a_vec, matchange, var):
    coeffs = matchange * a_vec
    pol = _sage_const_0 
    for i in range(n):
        pol = pol + ZZ(round(coeffs[i])) * var**i
    return pol

# Make a polynomial into a vector in Minkowski space
def make_vec(fval, matchange):
    coeffs = [_sage_const_0  for i in range(n)]
    if fval != _sage_const_0 :
        colist = lift(fval).coefficients()
        for i in range(len(colist)):
            coeffs[i] = ZZ(colist[i])
    return matchange * vector(coeffs)

# Multiplication in Minkowski space
def vecmul_poly(u, v, mat, matinv):
    poly_u = make_poly(u, matinv, z)
    poly_v = make_poly(v, matinv, z)
    poly_prod = poly_u * poly_v
    return make_vec(poly_prod, mat)

def initiate_sampler():
    global sampler
    print("Initiating Sampler.")
    sampler = DiscreteGaussianDistributionLatticeSampler(cmqq.transpose(), sig)
    print(f"Sampler initiated with sigma {RDF(sig)}")
    return True

def error_test(num):
    print(f"Testing error production for {num} samples.")
    errorlist = [sampler().norm().n() for _ in range(num)]
    meannorm = mean(errorlist)
    maxnorm = max(errorlist)
    print(f"Avg error norm: {RDF(meannorm/(sqrt(n)*sampler.sigma*sqrt(_sage_const_2 *pi)))} * sqrt(n)*s")
    return True

secret = _sage_const_0 
def create_secret():
    global secret
    secret = cm * random_vec(q, n)
    return True

samps = []
def create_samples(numsampsval):
    global samps
    samps = []
    print("Creating samples...")
    for i in range(numsampsval):
        samp = get_sample(cm, cmi, secret, q, key)
        samps.append(samp)
    print(f"Done creating {len(samps)} samples.")
    return True

def go_to_q(a_vec, matchange):
    pol = make_poly(a_vec, matchange, x)
    pol_eval = pol.subs(x=_sage_const_1 )
    return Zq(pol_eval)

def sanity_check():
    print("Initiating sanity check...")
    mat = cmi
    pvec1 = random_vec(q, n)
    vec1 = cm * pvec1
    pvec2 = random_vec(q, n)
    vec2 = cm * pvec2
    vprod2 = vecmul_poly(vec1, vec2, cm, cmi)
    first_thing = go_to_q(vprod2, mat)
    second_thing = go_to_q(vec1, mat) * go_to_q(vec2, mat)
    if first_thing == second_thing:
        print("Sanity confirmed.")
    else:
        print("!!! SANITY ERROR !!!")
    return True

def histoq(data):
    hist = [_sage_const_0  for i in range(_sage_const_10 )]
    zeroct = _sage_const_0 
    for datum in data:
        if datum == _sage_const_0 : zeroct += _sage_const_1 
        histbit = floor(ZZ(datum)*_sage_const_10 /q)
        if histbit > _sage_const_9 : histbit = _sage_const_9 
        hist[histbit] += _sage_const_1 
    return [hist, zeroct]

def histo(data, cmi_mat):
    return histoq([go_to_q(datum, cmi_mat) for datum in data])

lift_s = _sage_const_0 
def secret_mod_q():
    global lift_s
    lift_s = go_to_q(secret, cmi)
    print(f"Secret mod q: {lift_s}")
    return True

def alg2(reportrate, quickflag=False):
    print("Beginning algorithm 2.")
    numsamps = len(samps)
    a_vals = [go_to_q(s[_sage_const_0 ], cmi) for s in samps]
    b_vals = [go_to_q(s[_sage_const_1 ], cmi) for s in samps]
    
    winner = [[], _sage_const_0 ]
    
    for round_idx in range(_sage_const_2 ):
        if round_idx == _sage_const_0 :
            print("ROUND 1: Peeking at real secret.")
            iterat = [lift_s]
        else:
            print("ROUND 2: Running attack naively.")
            iterat = range(_sage_const_1000 ) if quickflag else range(q)
            
        possibles = []
        for g in iterat:
            if Mod(g, reportrate) == _sage_const_0 : print(f"Checking residue {g}")
            g_zq = Zq(g)
            potential = True
            ctr = _sage_const_0 
            while ctr < numsamps and potential:
                e = abs(lift(Zq(b_vals[ctr] - g_zq * a_vals[ctr])))
                if q/_sage_const_4  < e < _sage_const_3 *q/_sage_const_4 :
                    potential = False
                else:
                    ctr += _sage_const_1 
            
            if ctr >= winner[_sage_const_1 ]:
                if ctr > winner[_sage_const_1 ]: winner = [[g_zq], ctr]
                else: winner[_sage_const_0 ].append(g_zq)
            
            if potential: possibles.append(g_zq)

    print(f"Real secret mod q was: {lift_s}")
    if lift_s in possibles:
        print("Success! Secret found.")
        return True
    return False

def shebang(fval, qval, sval, numsampsval, numtrials, quickflag=False):
    global sig
    print("Welcome to the Ring-LWE Attack.")
    n_deg = fval.degree()
    
    setup_params(fval, qval, sval)
    prepare_matrices()
    
    initiate_sampler()
    count_successes = _sage_const_0 
    
    for trialnum in range(numtrials):
        print(f"\n--- TRIAL {trialnum} ---")
        create_secret()
        create_samples(numsampsval)
        sanity_check()
        secret_mod_q()
        if alg2(_sage_const_10000 , quickflag):
            count_successes += _sage_const_1 
            
    print(f"\nFinal Result: {count_successes}/{numtrials} successes.")
    return count_successes


# # gọi hàm ví dụ
f = y**_sage_const_4  + _sage_const_1       # đa thức cyclotomic bậc 4
q = _sage_const_101           # số nguyên tố
s = _sage_const_3             # sigma

shebang(f, q, s, numsampsval=_sage_const_50 , numtrials=_sage_const_5 , quickflag=True)

